### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup

### ISSUE THREAD

**Issue by ahmcode** [DepressingUtopian/VideoEditor#1]
Hi,

i have an error while opening the app and select a video. Here is the error log.

2020-05-29 00:26:10.916 14267-14267/com.project.videoeditor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.project.videoeditor, PID: 14267
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.project.videoeditor/com.project.videoeditor.activity.MainEditor}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3516)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3655)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2218)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7835)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
     Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
        at android.view.ViewGroup.addView(ViewGroup.java:5008)
        at android.view.ViewGroup.addView(ViewGroup.java:4990)
        at com.project.videoeditor.activity.MainEditor.onCreate(MainEditor.java:89)
        at android.app.Activity.performCreate(Activity.java:7967)
        at android.app.Activity.performCreate(Activity.java:7956)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3487)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3655) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2218) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:238) 
        at android.app.ActivityThread.main(ActivityThread.java:7835) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984) 

Will you solve and update the code? I still try to understand overall the code and how they works.

**Comment by Hedmor** [comment]
What version of OC do you use for testing? What is the extension of the video? If Android 10, then the approach to working with files has changed. In short, now it is not possible to get the full path to the file, only the file descriptor.

At the moment I am working on interface elements and individual functions for it. Android 10 support I will implement later.
This code is a prototype, its general style and variable naming change. Class architecture will be changed and comments added. Expect further repository updates!

**Comment by Hedmor** [comment]
I fixed the problem, the solution is in the prototype branch. It seems to work :)

**Comment by ahmcode** [comment]
> I fixed the problem, the solution is in the prototype branch. It seems to work :)

I already try the latest commit. Unfortunately, it doesn't works. 
Simply, i just modify code in the MainActivity.java:

`if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
                        ffmpegPath = UtilUri.safUriToFFmpegPath(this,selectedVideoUri);
                    else
                        ffmpegPath = UtilUri.getPath(this,selectedVideoUri);`

to

` ffmpegPath = UtilUri.getPath(this,selectedVideoUri);`

and now, it's works. I think UtilUri.safUriToFFmpegPath(this,selectedVideoUri); gives wrong filepath. So, the exoplayer can not play and preview the media.

**Comment by Hedmor** [comment]
> > I fixed the problem, the solution is in the prototype branch. It seems to work :)
> 
> I already try the latest commit. Unfortunately, it doesn't works.
> Simply, i just modify code in the MainActivity.java:
> 
> `if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) ffmpegPath = UtilUri.safUriToFFmpegPath(this,selectedVideoUri); else ffmpegPath = UtilUri.getPath(this,selectedVideoUri);`
> 
> to
> 
> ` ffmpegPath = UtilUri.getPath(this,selectedVideoUri);`
> 
> and now, it's works. I think UtilUri.safUriToFFmpegPath(this,selectedVideoUri); gives wrong filepath. So, the exoplayer can not play and preview the media.

Thank:) I'll see what's the matter. A lot of code in the garbage project. I delete it as it develops so be careful!
